# Generated by Django 3.2.15 on 2023-05-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='price',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
